
GET  http://localhost:7000/api/v1/

###
POST http://localhost:7000/api/v1/auth/signup
content-type: application/json

{
    "email": "longthanhlong@gmail.com",
    "fullName": "Nguyễn Thanh Long",
    "username": "thanhlong",
    "password": "test1234",
    "passwordConfirmation": "test1234"
}

###
POST http://localhost:7000/api/v1/auth/refresh_token
content-type: application/json

{
    "userId": "cc4fb0d3-a5ff-4708-94e7-b056ca83eedf"
}


###
POST http://localhost:7000/api/v1/auth/login
content-type: application/json

{
    "email": "longthanhlong@gmail.com",
    "password": "test1234"
}

###
DELETE  http://localhost:7000/api/v1/auth/logout
content-type: application/json

{
    "userId": "cc4fb0d3-a5ff-4708-94e7-b056ca83eedf"
}

###
GET http://localhost:7000/api/v1/users/profile_info?username=thanhlong
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiJjYzRmYjBkMy1hNWZmLTQ3MDgtOTRlNy1iMDU2Y2E4M2VlZGYiLCJpYXQiOjE2NjA0ODU2ODYsImV4cCI6MTY2MDQ4OTI4Nn0.5DZUzgTMMalnXIhmw9XMhnZtwim9nEhG6DAS9r0y_fc

###
POST http://localhost:7000/api/v1/posts
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiJjYzRmYjBkMy1hNWZmLTQ3MDgtOTRlNy1iMDU2Y2E4M2VlZGYiLCJpYXQiOjE2NTc4NzExNjMsImV4cCI6MTY1Nzk1NzU2M30.oXUzxPIth3V-2tEy7FLFXI4juljgAt3GisO87TMNFkY
content-type: application/json

{
    "note": "You made my day!"
}

###
GET http://localhost:7000/api/v1/posts
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiJjYzRmYjBkMy1hNWZmLTQ3MDgtOTRlNy1iMDU2Y2E4M2VlZGYiLCJpYXQiOjE2NTc4NzExNjMsImV4cCI6MTY1Nzk1NzU2M30.oXUzxPIth3V-2tEy7FLFXI4juljgAt3GisO87TMNFkY
content-type: application/json


###
PATCH http://localhost:7000/api/v1/posts/31484765-bf8f-4795-a3e6-ea1b337eca04
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiJjYzRmYjBkMy1hNWZmLTQ3MDgtOTRlNy1iMDU2Y2E4M2VlZGYiLCJpYXQiOjE2NTc4NzExNjMsImV4cCI6MTY1Nzk1NzU2M30.oXUzxPIth3V-2tEy7FLFXI4juljgAt3GisO87TMNFkY
content-type: application/json

{
    "note": "You made my day!!?"
}

###
DELETE  http://localhost:7000/api/v1/posts/31484765-bf8f-4795-a3e6-ea1b337eca04
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiJjYzRmYjBkMy1hNWZmLTQ3MDgtOTRlNy1iMDU2Y2E4M2VlZGYiLCJpYXQiOjE2NTc4NzExNjMsImV4cCI6MTY1Nzk1NzU2M30.oXUzxPIth3V-2tEy7FLFXI4juljgAt3GisO87TMNFkY
content-type: application/json
