
GET  http://localhost:7000

###
POST http://localhost:7000/auth/signUp
content-type: application/json

{
    "email": "testing5@gmail.com",
    "password": "test1234",
    "passwordConfirmation": "test1234"
}

###
POST http://localhost:7000/auth/signIn
content-type: application/json

{
    "email": "testing5@gmail.com",
    "password": "test1234"
}

###
GET http://localhost:7000/users/e730259e-5a62-48a6-bc9f-4c3bd10ad35c
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTQ4MjU5NjcsImV4cCI6MTY1NDgyOTU2N30.ukmiN3H8yxsihxfsJKei4sV44zq_ri3xClkK2NbJc1I
